<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Article;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $n
     * @param string $order
     * @return Article[]
     */
    public function getLastNthArticles($n, $order = "DESC") {
        $qb = $this->getEntityManager()->createQueryBuilder();

        return $qb->select("article")
            ->from("AppBundle:Article", "article")
            ->setMaxResults($n)
            ->orderBy("article.createdAt", $order)
            ->getQuery()
            ->getResult();
    }
}

?>
