<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastNthArticles($n, $order = "DESC") {
        $qb = $this->getEntityManager()->createQueryBuilder();

        return $qb->select("article")
            ->from("AppBundle:Article", "article")
            ->setMaxResults($n)
            ->orderBy("article.createdAt", $order)
            ->getQuery()
            ->getResult();
    }
}
